### ISSUE TITLE
Unhandled exception in Markdown.Avalonia.Markdown constructor

### ISSUE THREAD

**Issue by David-A-Blankenship** [whistyun/Markdown.Avalonia#166]
Avalonia 11.2.1 
.NET 8.0.7
Rocky Linux 8.9 64-bit

When opening a message box in Avalonia, I get a FileNotFoundException that is originating from the Markdown constructor. 

System.IO.FileNotFoundException: Unable to find the specified file.
   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
   at Interop.Sys.GetCwd()
   at Markdown.Avalonia.Markdown..ctor()
   at Markdown.Avalonia.MarkdownScrollViewer..ctor()

It looks like it is coming from here:

`        public Markdown()
        {
            _assetPathRoot = Environment.CurrentDirectory;
`
Unfortunately, I do not have good steps to reproduce this issue. One of my users is having this problem.

**Comment by CreateLab** [comment]
Do u see, that's now it separated packages for ms avalonia and for ms with markdown?

https://www.nuget.org/packages/MessageBox.Avalonia.Markdown/
