### ISSUE TITLE
`MarkdownScrollViewer` throws `InvalidOperationException` when using custom themes

### ISSUE THREAD

**Issue by Afanyiyu** [whistyun/Markdown.Avalonia#46]
The `MarkdownScrollViewer` control throws `InvalidOperationException` when using custom themes.

Here's my `App.xaml`:

```xaml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:metro="clr-namespace:Ruminoid.Common2.Metro;assembly=rmnd-metro"
             x:Class="Ruminoid.Toolbox.Shell.App">
    <Application.Styles>
        <metro:RuminoidMetro/> <!-- My custom RuminoidMetro style class -->
        <StyleInclude Source="/Controls/Styles/Generic.xaml"/> <!-- My project xaml file -->
    </Application.Styles>
</Application>

```

And when constructing `MarkdownScrollViewer` control, the `ThemeDetector` class skipped the `RuminoidMetro` class (√) and tried to get the `Host` of my local xaml file in project (x).

[ThemeDetector.cs#L59](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.Avalonia/Utils/ThemeDetector.cs#L59)

Exception:

```
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Host()
   at Markdown.Avalonia.Utils.ThemeDetector.get_IsFluentUsed()
   at Markdown.Avalonia.MarkdownScrollViewer..ctor()
   at Ruminoid.Toolbox.Plugins.Common.ConfigSections.Views.IntroConfigSection.!XamlIlPopulate(IServiceProvider , IntroConfigSection ) in D:\Projects\rmnd\Toolbox\plugins\rmbox-plugin-common\ConfigSections/Views/IntroConfigSection.axaml:line 1
   at Ruminoid.Toolbox.Plugins.Common.ConfigSections.Views.IntroConfigSection.!XamlIlPopulateTrampoline(IntroConfigSection )
   at Ruminoid.Toolbox.Plugins.Common.ConfigSections.Views.IntroConfigSection.InitializeComponent() in D:\Projects\rmnd\Toolbox\plugins\rmbox-plugin-common\ConfigSections\Views\IntroConfigSection.axaml.cs:line 29
   at Ruminoid.Toolbox.Plugins.Common.ConfigSections.Views.IntroConfigSection..ctor(JToken sectionConfig) in D:\Projects\rmnd\Toolbox\plugins\rmbox-plugin-common\ConfigSections\Views\IntroConfigSection.axaml.cs:line 24
```

QuickWatch window:

![image](https://user-images.githubusercontent.com/20179549/115521194-82afa580-a2bd-11eb-8424-a592a4cd83de.png)

## PR to fix this

#47

**Comment by whistyun** [comment]
Thank you for reporting this program and creating the pull request.
I will check other properties such as IsDefaultUsed and IsAvalonEditSetup before releasing

**Comment by whistyun** [comment]
v0.10.3 is released.
this version fix it.
